package dev.labintec.frontend.usuario.mdi;

import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 * Diálogo modal para la creación y edición de usuarios en la interfaz gráfica.
 * Permite ingresar los campos username y email, donde:
 *  - En modo creación (POST): ambos campos son editables
 *  - En modo edición (PUT): el username aparece bloqueado
 * @author Quique
 */
public class DialogPostPutUsuario extends javax.swing.JDialog {

    private boolean modoPost = true;

    /**
     * Creates new form PostPutUsuario
     */
    public DialogPostPutUsuario(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatosUsuario = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jButtonPostPut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Usuario");

        jPanelDatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos Usuario"));

        jLabelUsername.setText("Username (*)");

        jLabelEmail.setText("Email (*)");

        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyReleased(evt);
            }
        });

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelDatosUsuarioLayout = new javax.swing.GroupLayout(jPanelDatosUsuario);
        jPanelDatosUsuario.setLayout(jPanelDatosUsuarioLayout);
        jPanelDatosUsuarioLayout.setHorizontalGroup(
            jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsername)
                    .addComponent(jLabelEmail))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldUsername)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosUsuarioLayout.setVerticalGroup(
            jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername)
                    .addComponent(jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Acciones"));

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonPostPut.setText("Post/Put");
        jButtonPostPut.setEnabled(false);
        jButtonPostPut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPostPutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addComponent(jButtonPostPut)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalir)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonPostPut)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelDatosUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento que se dispara al liberar una tecla en el campo username.
     * Habilita o deshabilita el botón Post/Put según los datos ingresados.
     */
    private void jTextFieldUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_jTextFieldUsernameKeyReleased

    /**
     * Evento que se dispara al liberar una tecla en el campo email.
     * Habilita o deshabilita el botón Post/Put según los datos ingresados.
     */
    private void jTextFieldEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyReleased
        habilitarBoton();
    }//GEN-LAST:event_jTextFieldEmailKeyReleased

    /**
     * Evento del botón "Salir" que cierra el diálogo actual.
     */
    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    /**
     * Evento del botón "Post/Put" que crea o actualiza el usuario según el modo
     * actual del diálogo.
     * */
    private void jButtonPostPutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPostPutActionPerformed
        if (modoPost)
            crearUsuario();
        else
            actualizarUsuario();
        this.dispose();
    }//GEN-LAST:event_jButtonPostPutActionPerformed

    /**
     * Configura el modo del diálogo: creación (Post) o modificación (Put).
     * @param modoPost true para creación; false para modificación
     */
    public void setModoPost(boolean modoPost) {
        this.modoPost = modoPost;
        if (modoPost)
            jButtonPostPut.setText("Crear");
        else
            jButtonPostPut.setText("Actualizar");
    }

    /**
     * Ejecuta la operación de creación (POST) del usuario.
     */
    private void crearUsuario() {
        String username = jTextFieldUsername.getText().trim();
        String email = jTextFieldEmail.getText().trim();
        if (!esEmailValido(email)) {
            JOptionPane.showMessageDialog(this, "El email ingresado no es válido.");
            return;
        }
        String json = "{\"username\":\"" + username + "\", \"email\":\"" + email + "\"}";
        String respuesta = dev.labintec.frontend.usuario.cliente.ClienteRequestUsuarios.requestNewUsuario(json);
        if ("409".equals(respuesta))
            JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe.");
        else if (respuesta == null)
            JOptionPane.showMessageDialog(this, "Error de conexión con el servidor.");
        else
            JOptionPane.showMessageDialog(this, "Usuario creado correctamente.\n\n" + respuesta);
    }

    /**
     * Ejecuta la operación de actualización (PUT) del email del usuario.
     */
    private void actualizarUsuario() {
        String username = jTextFieldUsername.getText().trim();
        String email = jTextFieldEmail.getText().trim();
        if (!esEmailValido(email)) {
            JOptionPane.showMessageDialog(this, "El email ingresado no es válido.");
            return;
        }
        String respuesta = dev.labintec.frontend.usuario.cliente.ClienteRequestUsuarios.requestUpdateEmail(username, email);
        JOptionPane.showMessageDialog(this, "Usuario actualizado correctamente.\n\n" + respuesta);
    }

    /**
     * Habilita el botón Post/Put si ambos campos (username y email) están completos.
     */
    private void habilitarBoton() {
        String username = jTextFieldUsername.getText();
        String email = jTextFieldEmail.getText();
        if(!username.isEmpty() && !email.isEmpty())
            jButtonPostPut.setEnabled(true);
        else
            jButtonPostPut.setEnabled(false);
    }

    /**
     * Carga los datos del usuario en el formulario y bloquea edición del campo username.
     * @param username nombre de usuario (no editable)
     * @param email correo electrónico actual del usuario
     */
    public void setDatosUsuario(String username, String email) {
        jTextFieldUsername.setText(username);
        jTextFieldUsername.setEditable(false); // bloquea el campo username
        jTextFieldEmail.setText(email);
    }

    public static boolean esEmailValido(String email) {
        String regex = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";
        return email != null && email.matches(regex);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPostPut;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDatosUsuario;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}