/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package dev.labintec.frontend.Tramite.mdi;
/**
 * Diálogo modal para la creación de nuevos trámites.
 * Este JDialog actúa como contenedor principal de un JInternalFrame específico para ingresar datos,
 * y mantiene una referencia al frame padre que gestiona la tabla de trámites.
 *
 * @author matgr
 */
public class DialgNuevoTramite extends javax.swing.JDialog {
    private iFTablaTramite padre; 
        /**
     * Constructor del diálogo modal para ingresar nuevos trámites.
     * Inicializa los componentes de la interfaz y abre el frame interno de ingreso de datos.
     *
     * @param parent Ventana principal que actúa como owner del JDialog.
     * @param modal Bandera para establecer si el diálogo debe bloquear otras ventanas mientras está activo.
     * @param padre Referencia al frame padre (iFTablaTramite) para poder actualizar la tabla luego de ingresar datos.
     */
    public DialgNuevoTramite(java.awt.Frame parent, boolean modal,iFTablaTramite padre) {
        super(parent, modal);
        initComponents();
        this.padre=padre;
        inicio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(402, 143));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 143, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Inicializa y muestra el frame interno (iFrameNuevaT) dentro del JDialog.
     * Este frame contiene el formulario de ingreso del nuevo trámite.
     */
    private void inicio(){
        iFrameNuevaT ifn = new iFrameNuevaT(this,padre);
        jDesktopPane1.add(ifn);
        ifn.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
