/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package dev.labintec.frontend.Tramite.mdi;

    import dev.labintec.frontend.Tramite.cliente.ClienteRequestTransaction;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author matgr
 */
public class iFrameNuevaT extends javax.swing.JInternalFrame {
    private JDialog contenedor;
    private iFTablaTramite padre;
    /**
     * Creates new form iFrameNuevaT
     * @param referencia
     */
    public iFrameNuevaT(JDialog contenedor,iFTablaTramite padre) {
        this.contenedor=contenedor;
        this.padre=padre;
        initComponents();
    }
    public void mostrar(){
        this.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTipo = new javax.swing.JLabel();
        jTextTipo = new javax.swing.JTextField();
        jLabelEstatus = new javax.swing.JLabel();
        jTextEstatus = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        buttonCancelar = new javax.swing.JButton();

        jLabelTipo.setText("Tipo: (*)");

        jTextTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTipoActionPerformed(evt);
            }
        });
        jTextTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextTipoKeyReleased(evt);
            }
        });

        jLabelEstatus.setText("Estado: (*)");

        jTextEstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEstatusActionPerformed(evt);
            }
        });
        jTextEstatus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextEstatusKeyReleased(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setEnabled(false);
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTipo)
                    .addComponent(jLabelEstatus))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAgregar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jTextTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstatus)
                    .addComponent(jTextEstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregar)
                    .addComponent(buttonCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextTipoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTipoKeyReleased
        habilitar();
    }//GEN-LAST:event_jTextTipoKeyReleased

    private void jTextEstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEstatusActionPerformed

    private void jTextEstatusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextEstatusKeyReleased
        habilitar();
    }//GEN-LAST:event_jTextEstatusKeyReleased

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        String tipo = jTextTipo.getText();
        String estatus = jTextEstatus.getText();
        String json = "{ \"tipo\": \""+tipo+"\", \"estado\": \""+estatus+"\" }";
        String response = ClienteRequestTransaction.requestTransactionPostNuevo(json);
        JOptionPane.showMessageDialog(rootPane,"Tramite Creado Exitosamente", "Tramite Creado",JOptionPane.INFORMATION_MESSAGE);        
        contenedor.dispose();
        padre.inicio();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTipoActionPerformed

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
        contenedor.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed
     private void habilitar(){
        String username = jTextEstatus.getText();
        String email = jTextTipo.getText();
        if (!username.isEmpty() && !email.isEmpty()) {
            jButtonAgregar.setEnabled(true);
        }
        else{
            jButtonAgregar.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JLabel jLabelEstatus;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JTextField jTextEstatus;
    private javax.swing.JTextField jTextTipo;
    // End of variables declaration//GEN-END:variables
}
