/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.labintec.frontend;

import dev.labintec.frontend.Tramite.mdi.iFTablaTramite;
import dev.labintec.frontend.usuario.mdi.IFrameUsuario;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JInternalFrame;

/**
 *
 * @author matgr
 */
public class Prueba extends javax.swing.JFrame {
    /**
     * Creates new form jFTramite
     */
    public Prueba() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        desktopPanelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuUsuarios = new javax.swing.JMenu();
        jMenuItemGestion = new javax.swing.JMenuItem();
        MenuTramites = new javax.swing.JMenu();
        menuTramite = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPanelPrincipal.setMinimumSize(new java.awt.Dimension(582, 420));
        desktopPanelPrincipal.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                desktopPanelPrincipalComponentResized(evt);
            }
        });

        javax.swing.GroupLayout desktopPanelPrincipalLayout = new javax.swing.GroupLayout(desktopPanelPrincipal);
        desktopPanelPrincipal.setLayout(desktopPanelPrincipalLayout);
        desktopPanelPrincipalLayout.setHorizontalGroup(
            desktopPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        desktopPanelPrincipalLayout.setVerticalGroup(
            desktopPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuUsuarios.setText("Usuario");

        jMenuItemGestion.setText("Gestión de Usuarios");
        jMenuItemGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGestionActionPerformed(evt);
            }
        });
        jMenuUsuarios.add(jMenuItemGestion);

        jMenuBar1.add(jMenuUsuarios);

        MenuTramites.setText("Tramites");

        menuTramite.setText("Gestion de Tramites");
        menuTramite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTramiteActionPerformed(evt);
            }
        });
        MenuTramites.add(menuTramite);

        jMenuBar1.add(MenuTramites);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuTramiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTramiteActionPerformed
        cerrarFrames();
        // instancia del InternalFrame
        iFTablaTramite ift = new iFTablaTramite();

        // agregamos al desktop
        desktopPanelPrincipal.add(ift);
        
        ift.setSize(desktopPanelPrincipal.getSize());
        // Listener para ajustar el tamaño dinámicamente
        desktopPanelPrincipal.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                ift.setSize(desktopPanelPrincipal.getSize());
            }
        });

        // mostrar el frame
        ift.mostrar();

    }//GEN-LAST:event_menuTramiteActionPerformed

    private void jMenuItemGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGestionActionPerformed
        cerrarFrames();
        IFrameUsuario ifu = new IFrameUsuario();
        desktopPanelPrincipal.add(ifu);
        ifu.mostrar();
    }//GEN-LAST:event_jMenuItemGestionActionPerformed

    private void desktopPanelPrincipalComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_desktopPanelPrincipalComponentResized
        for (JInternalFrame frame : desktopPanelPrincipal.getAllFrames())
            frame.setSize(desktopPanelPrincipal.getSize());
    }//GEN-LAST:event_desktopPanelPrincipalComponentResized

    public static void mostrar() {
        new Prueba().setVisible(true);
    }
    private void cerrarFrames() {
    for (JInternalFrame frame : desktopPanelPrincipal.getAllFrames()) {
        frame.dispose(); // o frame.setVisible(false);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuTramites;
    private javax.swing.JDesktopPane desktopPanelPrincipal;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemGestion;
    private javax.swing.JMenu jMenuUsuarios;
    private javax.swing.JMenuItem menuTramite;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
